name: Validate xref

on:
  pull_request:
    paths:
      - 'modules/**'
      - 'antora.yml'
      - '.github/workflows/pr-validate-references.yml'

jobs:
  validate_xref:
    uses: bonitasoft/bonita-documentation-site/.github/workflows/_reusable_pr-validate-references.yml@chore/init-process-designer
    secrets: inherit
    with:
      component-name: process-designer
      fail-on-warning: true
      doc-site-branch: 'chore/init-process-designer'
